#!/bin/sh -e

# remove configuration

if [ "$1" = "purge" ]; then
    gconftool-2 --recursive-unset "/apps/navit"
fi

# Delete the .desktop and .service files in case the app-installer didn't.
rm -f /usr/share/applications/hildon/navit.desktop
rm -f /usr/share/dbus-1/services/org.navit-project.Navit.service

exit 0
